#!/usr/bin/env bash
#
# Creates a split tunnel for packets destined to Mullvad's SOCKS5 proxy.
# Useful for tunneling the traffic of specific applications.

die() {
	echo "[-] Error: $1" >&2
	exit 1
}

info() {
	echo "[+] $1"
}

validate_config() {
	[ -f "$1" ] || die "The config file $1 does not exist"
}

split_config() {
	INPUT_FILE="$1"
	CODE="$(basename ""${INPUT_FILE%.conf}"")"
	DNS="$(grep DNS ""$INPUT_FILE"" | cut -c 7-)"

	OUTPUT_FILE="split-$CODE.conf"

	info "Creating split tunnel for $CODE at $OUTPUT_FILE"

	cat "$INPUT_FILE" \
		| sed -E "s#AllowedIPs.*#AllowedIPs = 10.0.0.0/8, $DNS/32#" \
		> "$OUTPUT_FILE"
}

### Main ###

umask 077

if [ $# -eq 0 ]; then
	info "Usage: wg-split <Tunnel config> [Tunnel config]..."
	exit
fi

for config in $@; do
	validate_config "$config"
	split_config "$config"
done
